### ISSUE TITLE
Consider documenting how VACUUM works, or how space is reclaimed

### ISSUE THREAD

**Issue by dimaqq** [canonical/dqlite-docs#13]
Why I'm thinking it's worth it:

SQLite is a MVVC database, which means that conceptually, for a stale row to be evicted (or a whole lot of them during VACUUM), the database needs to know when all the "old" read transactions have finished.

SQLite VACUUM obtains an exclusive lock for this process, but that's not something naively feasible in a distributed database.

At the same time, operators (people) need to know when the space may be reclaimed, ideally across the cluster.

**Comment by cole-miller** [comment]
Right now, we don't support VACUUM, but it's a feature that we want to add in the future.

> SQLite VACUUM obtains an exclusive lock for this process, but that's not something naively feasible in a distributed database.

Yeah, indeed. The trickiest thing from dqlite's perspective is that VACUUM affects page numbers. That is, if you start with some database and do `VACUUM; INSERT INTO foo(n) VALUES (17)`, that will result in modifying some page `P`, whereas if you didn't do the `VACUUM` first the result would be modifying some different page `P'`. That means that if the leader does a `VACUUM` on its local database, and the followers don't follow suit, they will apply future changes to the database at the wrong page numbers. (Compare with SQLite's checkpoints, which don't impact page numbers, so all dqlite nodes can do them independently.)

This can be fixed by coordinating VACUUM through the raft log: we'd introduce a new kind of log entry that causes a database to be vacuumed when it's committed in raft. This will probably need to be triggered by a separate command in the wire protocol, not by sending `EXEC("VACUUM")`.

(Sorry for the delayed response!)
